knp_gaufrette:
    adapters:
        tasks_local:
            service:
                id: c0ntax_deployment_tasks.gaufrette.adapter.local

    filesystems:
        tasks:
            adapter: tasks_local
            alias: tasks_filesystem
